### ISSUE TITLE
How to use custom themes to make bold fonts change color

### ISSUE THREAD

**Issue by archerjok** [catppuccin/mdBook#100]
I want to use a custom theme to make the `*title*` modified font bold and change color, 
<font color=Blue>Title </font>
because there are a lot of places to use, so I don't want to use <font> in markdown syntax.
please tell me how to do it? There is a lack of instructions here.

**Comment by sgoudham** [comment]
Hey :wave:, you can accomplish this by using the [additional-css](https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=additional-css#html-renderer-options) tag to load your own custom CSS stylesheet to change the styling for the `h1` tag. 

I'd imagine you could include something like this:

```css
/* blue and bold h1 markdown headings */
h1 {
	color: blue
	font-weight: bold;
}
```

I'll be closing this issue as it's not relevant to this theme, hope you are able to figure out a solution to your problem!
