### ISSUE TITLE
How to totally uninstall catppuccin

### ISSUE THREAD

**Issue by nasuf** [catppuccin/mdBook#101]
I was trying to use catppuccin, it looks good on desktop web broswer. But somehow it was having issue on mobile broswer (tried on safari and chrome, side bar is not populating all the items). So i tried to uninstall catppuccin (just force reset commit version and uninstall catppuccin with `cargo uninstall mdbook-catppuccin` then `mdbook build`, but it's causing some other issues:
1. When I push my reverted changes to github it's running fine with default themes. But **locally** it's not loading default theme list and the default style looks weird as below
<img width="1025" alt="image" src="https://github.com/catppuccin/mdBook/assets/13514662/26febc32-f33d-4759-a4d5-7b4a2af3cb0a">
2. The categories in side bar can not be fold or expanded when clicking on arrows.

I tried to re-install rust entirely for cleaning the whole environment, and create new mdbook, but still it's not working properly on my local.. Just curious is there any solution to recover it ? Thanks

**Comment by sgoudham** [comment]
Hi :wave:, sorry to hear you're experiencing so many issues with this. 

The main responsibility of the `catppuccin-mdbook` binary is to simply transfer over the files listed in [src/bin/assets](https://github.com/catppuccin/mdBook/tree/main/src/bin/assets), and upon running `mdbook build` - it will check to see if the assets are out of date or not.

When `catppuccin-mdbook` transfers the files to your theme directory, it also modifies the `book.toml` to include the additional CSS files (along with automatically recognising the `index.hbs`) 

Realistically, all you should need to do is to remove the `index.hbs`, `catppuccin.css` and `catppuccin-admonish.css` files from your theme directory (and also remove the entries from your `book.toml`) and your book should have no trace of Catppuccin.

However, if new mdbooks are not locally working on your machine - then I'm concerned that there may be something deeper causing this.

**Comment by sgoudham** [comment]
As you mentioned your website, I scrolled through the commits and saw that you removed the files that I said in https://github.com/nasuf/nasuf.github.io/commit/a8e53d544b637de594f109d2afd4d91857faf323

Unfortunately, I can't give anymore tips other then removing those files as that is the entirety of the theme and I'll be closing this issue because of that. I hope you are able to resolve this issue!
