### ISSUE TITLE
Deprecate the `mdbook-catppuccin` Rust binary

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/mdBook#107]
## Background

It's about time I did this...

So, I created this plugin with the help of my good friend @nekowinston. It was my first ever "port" (before I was part of the Catppuccin organisation) and I was still very excited to do Rust projects to learn more about the language.

While I look very fondly on my time spent developing the binary and writing Rust, my opinion is that it has resulted in an entirely over-complicated solution that makes it much harder to maintain the Catppuccin mdBook theme. Granted, I think some of the complexity comes from the fact that mdBook's approach of custom themes but regardless, there are some issues with the state of the repository that make it demotivating and again, in my opinion, annoying to work on.

## Description

To clarify, the _theme_ is not getting deprecated but just the Rust binary that tries to automate the installation of the assets.

The main reason for the deprecation is that the themes cannot appear on the top bar of an mdBook without editing the built-in `index.hbs` template. This template is crucial to mdBook and the approach taken in this repository of shipping a vendored version can result in unintended issues cropping up.

The only approach going forward will be the "manual" installation which will require users to transfer over the assets and manually edit the `index.hbs` file for their version of mdBook that they are using. Instead of taking a gamble on the `index.hbs` file provided by this binary and hoping that it aligns with their own version of mdBook.

## Acceptance Criteria

- [x] Push out a MINOR version giving users a deprecation warning and that they should uninstall the binary before it stops working.
- [ ] Push out a MAJOR version removing all behaviour from the plugin, display a message that the automatic installation method has been removed and link users to the manual installation guide.
- [x] Update documentation so that users can manually install the assets step by step and inform them how to make edits to their own `index.hbs`.

**Comment by meator** [comment]
Hi, please update the `README.md` and remove references of the executable from it. The executable appears to be packaged in several places, which will require special attention when transitioning off the `mdbook-catppuccin install` install method.
