### ISSUE TITLE
Add example mdBook to show off colourscheme

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/mdBook#3]
## What
An example mdbook should live in the root directory of the repository. This book should also be deployed under GitHub Pages.

## Why
Providing a visual preview of the colour scheme will significantly enhance the user experience and offer easy access to the latest version of the extension. We should use the domain `mdbook.catppuccin.com`

## Acceptance Criteria
- [x] Example mdBook created with pages showcasing different types of highlights (headings, paragraphs, codeblocks etc)
- [x] GitHub Actions workflow for deploying to GitHub Pages
- [ ] Page deployed under `mdbook.catppuccin.com`

**Comment by NamesCode** [comment]
Hey, I'm interested in this

**Comment by sgoudham** [comment]
Thanks for being interested in contributing! Feel free to ping me on discord if you need any help or have any questions, happy to help 👍
