### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/mdBook#4]
## What
Documentation for other developers wanting to contribute should be included.

## Why
We want the repository to be as accessible as possible for developers looking to contribute. Contributing shouldn't require pre-requisite knowledge of all of the rust, so we should be kind and detail the commands needed.

## Acceptance Criteria
~~- [ ] Add `Contributing` section in the current README.md~~
    ~~- [ ] Thank the user for looking to contribute to the repository~~
    ~~- [ ] Link off to the current contributing guidelines defined in Catppuccin's `.github` repository~~
- [x] Add `Building Locally` section in the current README.md
    - [x] Instructions for building locally are clearly defined
    - [x] Make sure to specify versions of mdbook and rust used

The instructions for building locally are as follows:
### Building Locally

1. Install the latest version of rust on your preferred choice of operating system, we recommend
   using [rustup](https://rustup.rs/).

2. Clone the repository

   ```shell
   git clone https://github.com/catppuccin/mdBook
   ```

3. Navigate to root directory

   ```shell
   cd mdBook
   ```

4. Build the binary!

   ```shell
   cargo build --release
   ```

**Comment by NamesCode** [comment]
Will do

**Comment by NamesCode** [comment]
Gonna work on it later today

**Comment by NamesCode** [comment]
> Gonna work on it later today

Lies
