### ISSUE TITLE
Add a reminder on README for those who want to replace all the built-in themes

### ISSUE THREAD

**Issue by lpnh** [catppuccin/mdBook#99]
In the [mdBook documentation](https://rust-lang.github.io/mdBook/format/theme/index.html) there's a reminder for those who want to replace all the built-in themes:

"If you completely replace all built-in themes, be sure to also set [output.html.preferred-dark-theme](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options) in the config, which defaults to the built-in navy theme."

I suggest adding the same reminder to the 'How can I remove the default themes?' section in the FAQ.

Additionally, 'default-theme' isn't mentioned, but perhaps it should also be set to new values alongside 'preferred-dark-theme'?

Here's how I set them for my project:

```
[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
```

I would like to take this opportunity to thank everyone for the great work on this repository.

**Comment by sgoudham** [comment]
Hey :wave:

I've updated the FAQ as per your suggestions! Thanks for the suggestion and kind words!
